services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - persistent
    ports:
      - ${PORT:-8080}:8080
      - ${GRPC-PORT:-50051}:50051
    restart: unless-stopped

  persistent:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-product_service}
      POSTGRES_USER: ${DB_USER:-law-a-1}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - ${DB_PORT:-5432}:5432
    restart: unless-stopped

  reverse-proxy:
    build: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - persistent
      - app
